/* ============================================================
   ELEVATED STATES PROJECT — POLICY ATLAS DATA
   ------------------------------------------------------------
   Single source of truth. Every layer, the time-slider, and the
   ask-the-map engine read from STATES / CITIES / CHURCHES below.

   ACCURACY MODEL: each state carries a "verified" flag. verified:1
   states have been re-sourced against authoritative trackers with a
   "src" (sources) and "updated" (as-of date); verified:0 states are
   still best-effort ILLUSTRATIVE placeholders. Educational only, not
   legal advice.

   ---- PER-STATE SCHEMA (STATES[name] = {...}) ----
   o     : Number 0–100   composite "openness" index (relief height)
   can   : "rec" | "med" | "lowthc" | "illegal"    cannabis status
   recY,medY : Number|null   year rec / comprehensive medical began
   psi   : "legal" | "decrim" | "none"    psilocybin status;  psiY : year
   ibo   : "active" | "considering" | "none"    ibogaine initiative
   ket   : "open" | "clinic"    ketamine access nuance
   mdma  : "trial" | "rtt" | "none"    MDMA
   rfra  : 0|1    state Religious Freedom Restoration Act
   fts   : "legal" | "illegal"    fentanyl test strips
   ssp   : "yes" | "limited" | "no"    syringe-services programs
   gsl   : "yes" | "limited" | "no"    Good Samaritan overdose-immunity law
   rsch  : "active" | "emerging" | "none"    psychedelic research;  rschN : institutions
   ---- NEW capabilities ----
   mom   : "high" | "med" | "low" | "none" | "na"   reform momentum / trajectory
   momN  : String   what's pending / moving
   tribal: 0|1      tribal or notable local legalization a state map would miss;  tribalN : note
   verified : 0|1   has this state been re-sourced?
   src   : String   sources (verified states)
   updated : String   as-of date (verified states)

   OPENNESS INDEX (o) is COMPUTED from the sourced fields — weights (max 100):
   cannabis 30 (rec/med/lowthc) · psilocybin 25 (legal/decrim) · ibogaine+MDMA access 10 ·
   research 10 · harm reduction 15 (FTS+SSP+Good Samaritan) · reform momentum 10.
   ============================================================ */

const STATES = {
"Alabama":{o:39,can:"med",recY:null,medY:2021,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"no",gsl:"limited",rsch:"active",rschN:"UAB (Dept. of Psychiatry)",mom:"low",momN:"Medical cannabis operationalizing after litigation (first dispensary June 2026); no psychedelic reform",tribal:0,tribalN:"",verified:1,src:"AMCC; Alabama Reflector; UAB",updated:"2026-07"},
"Alaska":{o:49,can:"rec",recY:2014,medY:1998,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"limited",rsch:"none",rschN:"",mom:"med",momN:"Psychedelic task force delivered pro-reform recommendations (Feb 2026); citizen decrim initiative slipped to 2028",tribal:0,tribalN:"",verified:1,src:"Marijuana Moment; Alaska Public; Ballotpedia",updated:"2026-07"},
"Arizona":{o:69,can:"rec",recY:2020,medY:2010,psi:"none",psiY:null,ibo:"active",ket:"open",mdma:"rtt",rfra:1,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"Scottsdale Research Institute (state-funded psilocybin RCT)",mom:"med",momN:"$5M state ibogaine study (2025) + $5M psilocybin research grant + follow-FDA MDMA law; direct-access service-center bill vetoed 2024",tribal:0,tribalN:"",verified:1,src:"AZ Legislature; Marijuana Moment; Reason",updated:"2026-07"},
"Arkansas":{o:36,can:"med",recY:null,medY:2016,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"no",gsl:"yes",rsch:"emerging",rschN:"UAMS",mom:"low",momN:"Rec rejected 2022; 2024 expansion votes voided by state Supreme Court; restrictive trajectory",tribal:0,tribalN:"",verified:1,src:"MPP; Ballotpedia; Arkansas Advocate",updated:"2026-07"},
"California":{o:78,can:"rec",recY:2016,medY:1996,psi:"decrim",psiY:2019,ibo:"none",ket:"open",mdma:"trial",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"UC Berkeley / UCSF / UCLA / Stanford",mom:"med",momN:"Statewide decrim vetoed (SB58, 2023); SB751 therapeutic-access bill advancing 2026; ongoing city decrim",tribal:0,tribalN:"",verified:1,src:"MPP; Psychedelic Alpha; CA DHCS",updated:"2026-07"},
"Colorado":{o:93,can:"rec",recY:2012,medY:2000,psi:"legal",psiY:2022,ibo:"considering",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"CU Denver / CU Anschutz / Naropa",mom:"high",momN:"Regulated psilocybin healing-center program rolling out (enacted, operational)",tribal:0,tribalN:"",verified:1,src:"MPP; CO Natural Medicine Division; Psychedelic Alpha",updated:"2026-02"},
"Connecticut":{o:63,can:"rec",recY:2021,medY:2012,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"trial",rfra:1,fts:"legal",ssp:"yes",gsl:"limited",rsch:"active",rschN:"Yale / UConn Health",mom:"med",momN:"Psychedelic expanded-access pilot (veterans/first responders) expanded & signed June 2026; broad decrim stalled",tribal:1,tribalN:"Mashantucket Pequot signed CT's first tribal-state cannabis compact (Foxwoods retail planned)",verified:1,src:"MPP; Marijuana Moment; CT DPH",updated:"2026-07"},
"Delaware":{o:48,can:"rec",recY:2023,medY:2011,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"none",rschN:"",mom:"low",momN:"Adult-use retail launched Aug 2025; no psychedelic reform",tribal:0,tribalN:"",verified:1,src:"DE.gov; MPP; LAPPA",updated:"2026-07"},
"District of Columbia":{o:66,can:"rec",recY:2014,medY:2010,psi:"decrim",psiY:2020,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"",mom:"low",momN:"Initiative 81 decriminalized entheogens (2020); congressional riders block cannabis retail + further reform",tribal:0,tribalN:"",verified:1,src:"MPP; Psychedelic Alpha",updated:"2026-07"},
"Florida":{o:44,can:"med",recY:null,medY:2016,psi:"none",psiY:null,ibo:"none",ket:"clinic",mdma:"none",rfra:1,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"University of Florida / USF",mom:"med",momN:"Adult-use Amendment 3 got 56% in 2024 (short of 60%); renewed 2026 ballot effort; large mature medical market",tribal:0,tribalN:"",verified:1,src:"Ballotpedia; FL DOH; Florida Phoenix",updated:"2026-07"},
"Georgia":{o:33,can:"lowthc",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"Emory",mom:"med",momN:"Psychedelic/ketamine clinic-regulation law (HB 717) enacted 2026; cannabis stuck at low-THC oil",tribal:0,tribalN:"",verified:1,src:"MPP; Healthesystems; Little Health Law",updated:"2026-07"},
"Hawaii":{o:44,can:"med",recY:null,medY:2000,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"University of Hawaii (JABSOM)",mom:"med",momN:"Rec cannabis repeatedly blocked by House; psychedelic study task-force bills advancing (SB 3199); Governor supportive",tribal:0,tribalN:"",verified:1,src:"MPP; Marijuana Moment; ACLU-HI",updated:"2026-07"},
"Idaho":{o:11,can:"illegal",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"no",gsl:"limited",rsch:"none",rschN:"",mom:"low",momN:"Among strictest; HJR 4 (Nov 2026 vote) would bar citizen initiatives on cannabis/psychoactives; 2026 medical-cannabis ballot contested",tribal:0,tribalN:"",verified:1,src:"MPP; Idaho Capital Sun; Ballotpedia",updated:"2026-07"},
"Illinois":{o:64,can:"rec",recY:2019,medY:2013,psi:"none",psiY:null,ibo:"considering",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"Rush University / U of Illinois",mom:"med",momN:"CURE Act (decrim + licensed service centers) reintroduced 2025-26, stalled; nothing enacted",tribal:0,tribalN:"",verified:1,src:"MPP; Marijuana Moment; IDPH",updated:"2026-07"},
"Indiana":{o:19,can:"illegal",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"illegal",ssp:"limited",gsl:"yes",rsch:"emerging",rschN:"IU (state psilocybin research fund)",mom:"med",momN:"State psilocybin research fund enacted 2023 (veterans/first responders); syringe extension advancing 2026; cannabis bills stalled",tribal:0,tribalN:"",verified:1,src:"Marijuana Moment; Indiana Capital Chronicle; KFF",updated:"2026-05"},
"Iowa":{o:26,can:"lowthc",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"illegal",ssp:"no",gsl:"limited",rsch:"active",rschN:"University of Iowa (Psychedelic Research Program)",mom:"med",momN:"Supervised medical psilocybin bill (HF 978) passed House 2026, advancing in Senate; dispensary expansion signed; FTS/SSP still banned",tribal:0,tribalN:"",verified:1,src:"Iowa Capital Dispatch; MPP; Filter",updated:"2026-07"},
"Kansas":{o:9,can:"illegal",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"no",gsl:"limited",rsch:"none",rschN:"",mom:"none",momN:"Among most restrictive; no medical program; narrow FDA-contingent psilocybin bill; incremental harm reduction only",tribal:0,tribalN:"",verified:1,src:"MPP; KCUR; CBD Oracle",updated:"2026-07"},
"Kentucky":{o:50,can:"med",recY:null,medY:2025,psi:"none",psiY:null,ibo:"active",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"University of Kentucky",mom:"med",momN:"Medical cannabis sales began Jan 2026; ibogaine research law (SB 77) enacted April 2026 but ~$21M funding stripped (unfunded)",tribal:0,tribalN:"",verified:1,src:"MPP; KY Legislature; NKY Tribune",updated:"2026-07"},
"Louisiana":{o:52,can:"med",recY:null,medY:2015,psi:"none",psiY:null,ibo:"active",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"limited",gsl:"yes",rsch:"emerging",rschN:"LDH-named academic health centers (TBD)",mom:"high",momN:"3-substance psychedelic-assisted therapy research initiative (SB 43: psilocybin/ibogaine/MDMA) effective Aug 2026; hemp tightened",tribal:0,tribalN:"",verified:1,src:"Marijuana Moment; MPP; Network for Public Health Law",updated:"2026-07"},
"Maine":{o:48,can:"rec",recY:2016,medY:1999,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"none",rschN:"",mom:"low",momN:"Psilocybin decrim (LD 1034) repeatedly filed, narrowly failed enactment 2025",tribal:0,tribalN:"",verified:1,src:"MPP; Filter; Network for Public Health Law",updated:"2026-07"},
"Maryland":{o:61,can:"rec",recY:2022,medY:2013,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"Johns Hopkins",mom:"med",momN:"State psychedelics task force endorsed clinical + adult access (Nov 2025); 2026 bills pending; Johns Hopkins flagship research",tribal:0,tribalN:"",verified:1,src:"MPP; Maryland Matters; Johns Hopkins",updated:"2026-07"},
"Massachusetts":{o:81,can:"rec",recY:2016,medY:2012,psi:"decrim",psiY:2021,ibo:"considering",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"MGH / McLean / Harvard",mom:"high",momN:"House passed psychedelic-therapy pilot July 2026 (pending Senate); statewide Question 4 failed 2024; ibogaine bills advancing",tribal:1,tribalN:"7 cities deprioritized entheogens (Somerville, Cambridge, Northampton, Salem, Amherst, Provincetown, Easthampton)",verified:1,src:"MPP; Marijuana Moment; Ballotpedia",updated:"2026-07"},
"Michigan":{o:81,can:"rec",recY:2018,medY:2008,psi:"decrim",psiY:2020,ibo:"considering",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"University of Michigan (Michigan Psychedelic Center)",mom:"high",momN:"Concurrent 2026 bills ($50M ibogaine HB 6020, statewide psilocybin SB 631, harm-reduction formalization); 5 cities already decriminalized",tribal:1,tribalN:"5 municipalities decriminalized entheogens (Ann Arbor, Detroit, Hazel Park, Ferndale, Ypsilanti)",verified:1,src:"MPP; Michigan Advance; U-M",updated:"2026-07"},
"Minnesota":{o:59,can:"rec",recY:2023,medY:2014,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"limited",rsch:"active",rschN:"University of Minnesota",mom:"med",momN:"Psychedelic Medicine Task Force (Jan 2025) urged regulated access; 2026 psilocybin bills advancing; not enacted",tribal:1,tribalN:"White Earth Nation opened off-reservation adult-use stores via 2025 state compact; Red Lake Nation dispensary",verified:1,src:"MPP; MN OCM; MDH",updated:"2026-07"},
"Mississippi":{o:45,can:"med",recY:null,medY:2022,psi:"none",psiY:null,ibo:"active",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"no",gsl:"yes",rsch:"emerging",rschN:"(ibogaine research consortium; institution TBD)",mom:"med",momN:"$5M ibogaine clinical-trial funding (HB 314) enacted March 2026 (Texas-anchored consortium); no rec movement; SSPs still banned",tribal:0,tribalN:"",verified:1,src:"Mississippi Today; Magnolia Tribune; MPP",updated:"2026-07"},
"Missouri":{o:54,can:"rec",recY:2022,medY:2018,psi:"none",psiY:null,ibo:"considering",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"no",gsl:"yes",rsch:"emerging",rschN:"University of Missouri",mom:"med",momN:"Psilocybin/ibogaine veteran research bill (HB 1643/SB 1682) passed House 2026, final passage unconfirmed",tribal:0,tribalN:"",verified:1,src:"MPP; Marijuana Moment; Missouri Independent",updated:"2026-07"},
"Montana":{o:43,can:"rec",recY:2020,medY:2004,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"limited",gsl:"limited",rsch:"none",rschN:"",mom:"low",momN:"Cannabis mature (license moratorium to 2027); psychedelic reform stalled since 2023",tribal:1,tribalN:"Salish & Kootenai conformed to state rec law; Blackfeet Nation decriminalized medical for members; 2025 law allows state-tribal compacts",verified:1,src:"MPP; NORML; Montana Free Press",updated:"2026-07"},
"Nebraska":{o:32,can:"med",recY:null,medY:2024,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"no",gsl:"limited",rsch:"none",rschN:"",mom:"med",momN:"Voter-approved medical cannabis (2024) being implemented amid litigation; capped at 12 dispensaries; no psychedelic reform",tribal:1,tribalN:"Omaha Tribe legalized/regulates medical + adult-use cannabis (Title 51, eff. July 2025)",verified:1,src:"MPP; Nebraska Examiner; NORML",updated:"2026-07"},
"Nevada":{o:59,can:"rec",recY:2016,medY:2000,psi:"none",psiY:null,ibo:"considering",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"UNLV",mom:"med",momN:"Psychedelic working group urged regulated access; pilot (AB 378) died 2025; biennial legislature — next chance 2027",tribal:0,tribalN:"",verified:1,src:"Marijuana Moment; NV Legislature; Nevada Independent",updated:"2026-07"},
"New Hampshire":{o:36,can:"med",recY:null,medY:2013,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"none",rschN:"",mom:"low",momN:"Legalization repeatedly passes House, dies in Senate; psilocybin penalty-reduction tabled 2025 (only New England state without rec)",tribal:0,tribalN:"",verified:1,src:"MPP; NH Bulletin; Marijuana Moment",updated:"2026-07"},
"New Jersey":{o:73,can:"rec",recY:2020,medY:2010,psi:"decrim",psiY:2021,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"Rutgers / Princeton",mom:"high",momN:"Hospital-based psilocybin pilot enacted Jan 2026 ($6M, 3 hospitals); new state advisory board",tribal:0,tribalN:"",verified:1,src:"MPP; McCarter; NJ Governor",updated:"2026-07"},
"New Mexico":{o:90,can:"rec",recY:2021,medY:2007,psi:"legal",psiY:2025,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"UNM School of Medicine",mom:"high",momN:"Medical psilocybin program (SB 219) building ahead of schedule — first patient sessions targeted end of 2026",tribal:1,tribalN:"Navajo Nation (spans NM/AZ/UT) cannabis remains illegal under tribal code — state map overstates tribal-land access",verified:1,src:"NM DOH; Source NM; NM Legislature",updated:"2026-07"},
"New York":{o:68,can:"rec",recY:2021,medY:2014,psi:"none",psiY:null,ibo:"considering",ket:"open",mdma:"trial",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"Mount Sinai / NYU Langone",mom:"med",momN:"Multiple psilocybin/ibogaine bills in committee (A2142 medical psilocybin); deep research base; none enacted",tribal:1,tribalN:"Tribal cannabis retail on sovereign land (St. Regis Mohawk, Shinnecock) outside state OCM licensing",verified:1,src:"MPP; NY Senate; OASAS",updated:"2026-07"},
"North Carolina":{o:26,can:"illegal",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"UNC / Duke",mom:"med",momN:"Compassionate Care Act (medical cannabis) + HEAL Act psychedelic research — introduced, not enacted",tribal:1,tribalN:"EBCI (Cherokee) adult-use cannabis on the Qualla Boundary",verified:1,src:"MPP; Psychedelic Alpha; NC DHHS",updated:"2026-07"},
"North Dakota":{o:31,can:"med",recY:null,medY:2016,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"illegal",ssp:"yes",gsl:"yes",rsch:"none",rschN:"",mom:"low",momN:"Rec rejected 3x (2018/22/24); only a narrow FDA-contingent psilocybin rescheduling (SB 2064, 2025)",tribal:1,tribalN:"MHA Nation (Fort Berthold) decriminalized medical cannabis (2025); tribes may legalize independently",verified:1,src:"MPP; ND Legislature; Ballotpedia",updated:"2026-07"},
"Ohio":{o:62,can:"rec",recY:2023,medY:2016,psi:"none",psiY:null,ibo:"considering",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"limited",rsch:"active",rschN:"Ohio State (Center for Psychedelic Drug Research & Education)",mom:"med",momN:"Ibogaine study committee created (FY26-27 budget); OSU research strong; but cannabis tightening (SB 56, local moratoriums)",tribal:0,tribalN:"",verified:1,src:"MPP; Ohio Capital Journal; OSU",updated:"2026-07"},
"Oklahoma":{o:48,can:"med",recY:null,medY:2018,psi:"none",psiY:null,ibo:"active",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"limited",gsl:"yes",rsch:"emerging",rschN:"(ibogaine research consortium; institution TBD)",mom:"med",momN:"Ibogaine clinical-trial law (HB 3834, Breakthrough Therapy Act) effective Nov 2026; rec ballot efforts collapsed; syringe-program sunset looming",tribal:0,tribalN:"",verified:1,src:"Marijuana Moment; KOSU; MPP",updated:"2026-07"},
"Oregon":{o:90,can:"rec",recY:2014,medY:1998,psi:"legal",psiY:2020,ibo:"none",ket:"open",mdma:"trial",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"OHSU",mom:"med",momN:"Psilocybin services program operational (fine-tuning); 2020 drug-decrim rolled back in 2024",tribal:0,tribalN:"",verified:1,src:"Oregon Health Authority; Psychedelic Alpha; DPA",updated:"2026-Q1"},
"Pennsylvania":{o:42,can:"med",recY:null,medY:2016,psi:"none",psiY:null,ibo:"considering",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"limited",gsl:"yes",rsch:"emerging",rschN:"Penn / Pitt",mom:"low",momN:"Adult-use passed House May 2025, killed in Senate committee; medical-only; psychedelic/ibogaine bills introduced only",tribal:0,tribalN:"",verified:1,src:"MPP; MJBizDaily; ACLU-PA",updated:"2026-07"},
"Rhode Island":{o:65,can:"rec",recY:2022,medY:2006,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"trial",rfra:1,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"Brown University",mom:"med",momN:"Nation's first state-sanctioned overdose-prevention center (opened Dec 2024); Brown psychedelic research; statewide psilocybin reform stalled",tribal:0,tribalN:"",verified:1,src:"MPP; Prevent Overdose RI; Marijuana Moment",updated:"2026-07"},
"South Carolina":{o:28,can:"illegal",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"trial",rfra:1,fts:"legal",ssp:"no",gsl:"limited",rsch:"active",rschN:"MUSC",mom:"med",momN:"Compassionate Care Act (medical cannabis) passes Senate repeatedly, stuck in House; syringe bill pending; strong MUSC MDMA research",tribal:0,tribalN:"",verified:1,src:"SC Legislature; MPP; MUSC",updated:"2026-07"},
"South Dakota":{o:32,can:"med",recY:null,medY:2020,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"no",gsl:"limited",rsch:"none",rschN:"",mom:"med",momN:"Conditional psilocybin trigger law (HB 1099) enacted 2026 (FDA/DEA-contingent); rec rejected 3x",tribal:1,tribalN:"Oglala Sioux (Pine Ridge) legalized medical + adult-use on tribal land; Flandreau Santee Sioux medical dispensary",verified:1,src:"SD Searchlight; SD Legislature; MPP",updated:"2026-07"},
"Tennessee":{o:36,can:"lowthc",recY:null,medY:null,psi:"none",psiY:null,ibo:"active",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"Vanderbilt",mom:"low",momN:"Ibogaine research pathway enacted 2026 (veterans); cannabis restrictive, hemp/THC being tightened",tribal:0,tribalN:"",verified:1,src:"MPP; Fox17; Nashville Banner",updated:"2026-07"},
"Texas":{o:53,can:"med",recY:null,medY:2015,psi:"none",psiY:null,ibo:"active",ket:"open",mdma:"trial",rfra:1,fts:"illegal",ssp:"limited",gsl:"limited",rsch:"active",rschN:"UTMB / UTHealth / Baylor",mom:"high",momN:"$50M state ibogaine research initiative (2025, largest worldwide) + medical cannabis expanded 2025",tribal:0,tribalN:"",verified:1,src:"MPP; Texas Tribune; UTMB; KFF",updated:"2026-03"},
"Utah":{o:76,can:"med",recY:null,medY:2018,psi:"legal",psiY:2024,ibo:"none",ket:"open",mdma:"trial",rfra:0,fts:"legal",ssp:"yes",gsl:"limited",rsch:"active",rschN:"University of Utah Health / Intermountain Health",mom:"med",momN:"Hospital psilocybin + MDMA pilot (SB 266) live at U of Utah & Intermountain (limited; 3-yr sunset 2027); follow-FDA law (SB 83, 2026)",tribal:0,tribalN:"",verified:1,src:"Marijuana Moment; Salt Lake Tribune; Psychedelic Alpha",updated:"2026-07"},
"Vermont":{o:59,can:"rec",recY:2018,medY:2004,psi:"none",psiY:null,ibo:"considering",ket:"clinic",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"emerging",rschN:"University of Vermont (Osher Center)",mom:"med",momN:"Burlington overdose-prevention center authorized (not yet open); ibogaine study bill 2026; psilocybin stalled at study stage",tribal:0,tribalN:"",verified:1,src:"MPP; VT Legislature; Drug Policy Alliance",updated:"2026-07"},
"Virginia":{o:55,can:"rec",recY:2021,medY:2020,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"limited",gsl:"limited",rsch:"emerging",rschN:"VCU / UVA",mom:"high",momN:"Retail cannabis framework set for July 2027; psilocybin FDA-trigger law (reschedule on federal approval) signed April 2026",tribal:0,tribalN:"",verified:1,src:"MPP; VA Governor; Marijuana Moment",updated:"2026-07"},
"Washington":{o:77,can:"rec",recY:2012,medY:1998,psi:"decrim",psiY:2021,ibo:"considering",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"yes",gsl:"yes",rsch:"active",rschN:"University of Washington (NTAP)",mom:"med",momN:"Medical psilocybin act passed Senate but died before 2026 cutoff; UW research pilot live; ibogaine study bill pending",tribal:1,tribalN:"22 of 29 tribes hold cannabis compacts; Suquamish signed the first US state-tribal compact",verified:1,src:"WA HCA; Marijuana Moment; UW NTAP",updated:"2026-07"},
"West Virginia":{o:39,can:"med",recY:null,medY:2017,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:0,fts:"legal",ssp:"limited",gsl:"yes",rsch:"emerging",rschN:"WVU Rockefeller Neuroscience Institute",mom:"low",momN:"Medical-only; syringe-services restrictive (SB 334); legislative activity limited to edibles debate",tribal:0,tribalN:"",verified:1,src:"MPP; WVU; Governing",updated:"2026-07"},
"Wisconsin":{o:30,can:"illegal",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"trial",rfra:0,fts:"legal",ssp:"yes",gsl:"limited",rsch:"active",rschN:"UW-Madison (Transdisciplinary Center) / Usona Institute",mom:"low",momN:"Repeated medical + legalization bills (~86% support) blocked by GOP majority; several cities decriminalized; no psilocybin bills",tribal:0,tribalN:"",verified:1,src:"MPP; NORML; UW-Madison",updated:"2026-07"},
"Wyoming":{o:14,can:"illegal",recY:null,medY:null,psi:"none",psiY:null,ibo:"none",ket:"open",mdma:"none",rfra:1,fts:"legal",ssp:"no",gsl:"limited",rsch:"emerging",rschN:"University of Wyoming (School of Pharmacy, preclinical)",mom:"none",momN:"No reform advanced 2023-26; became the last state to enact a Good Samaritan law (2025); ballot initiatives failed distribution requirement",tribal:1,tribalN:"Wind River: Northern Arapaho voted to legalize/decriminalize medical cannabis (~2021; current program unverified)",verified:1,src:"MPP; WY Legislature; WyoFile",updated:"2026-07"}
};

const CITIES = [{"n":"Denver, CO","lat":39.74,"lon":-104.99,"y":2019},{"n":"Oakland, CA","lat":37.8,"lon":-122.27,"y":2019},{"n":"Santa Cruz, CA","lat":36.97,"lon":-122.03,"y":2020},{"n":"Ann Arbor, MI","lat":42.28,"lon":-83.74,"y":2020},{"n":"Washington, DC","lat":38.9,"lon":-77.04,"y":2020},{"n":"Cambridge, MA","lat":42.37,"lon":-71.11,"y":2021},{"n":"Somerville, MA","lat":42.39,"lon":-71.1,"y":2021},{"n":"Northampton, MA","lat":42.32,"lon":-72.63,"y":2021},{"n":"Seattle, WA","lat":47.61,"lon":-122.33,"y":2021},{"n":"Detroit, MI","lat":42.33,"lon":-83.05,"y":2021},{"n":"Arcata, CA","lat":40.87,"lon":-124.08,"y":2021},{"n":"San Francisco, CA","lat":37.77,"lon":-122.42,"y":2022},{"n":"Minneapolis, MN","lat":44.98,"lon":-93.27,"y":2023},{"n":"Berkeley, CA","lat":37.87,"lon":-122.27,"y":2023},{"n":"Amherst, MA","lat":42.37,"lon":-72.52,"y":2021},{"n":"Easthampton, MA","lat":42.27,"lon":-72.67,"y":2021}];

const CHURCHES = [{"n":"UDV · Santa Fe, NM","lat":35.69,"lon":-105.94,"y":2006},{"n":"Santo Daime · Ashland, OR","lat":42.19,"lon":-122.71,"y":2009}];

if (typeof module !== "undefined") { module.exports = { STATES, CITIES, CHURCHES }; }
